# Generated by Django 3.2.4 on 2021-08-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cover', models.URLField()),
                ('platforms', models.CharField(max_length=50)),
                ('genres', models.CharField(max_length=20)),
                ('release_dates', models.DateField()),
                ('companies', models.CharField(max_length=50)),
                ('companies_developer', models.BooleanField()),
                ('companies_publisher', models.BooleanField()),
                ('summary', models.CharField(max_length=1500)),
                ('age_rating_category', models.IntegerField()),
                ('age_rating_rating', models.IntegerField()),
            ],
        ),
    ]
