# Generated by Django 3.2.4 on 2021-08-12 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamepicker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='release_dates',
            new_name='first_release_date',
        ),
    ]
