# Generated by Django 3.2.4 on 2021-08-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepicker', '0002_rename_release_dates_game_first_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='first_release_date',
            field=models.CharField(max_length=20),
        ),
    ]
