# Generated by Django 3.2.4 on 2021-08-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepicker', '0003_alter_game_first_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
