# Generated by Django 3.2.4 on 2021-08-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepicker', '0004_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
