# Generated by Django 3.2.4 on 2021-08-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamepicker', '0005_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name_and_date',
            field=models.CharField(default=1, max_length=210),
            preserve_default=False,
        ),
    ]
